version: "3" 
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello123#
      MYSQL_DATABASE: DemoDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: Hello123#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: Hello123#
    ports:
      - "8088:80"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Hello123#
      WORDPRESS_DB_NAME: DemoDB
    volumes:
      ["./wordpress:/var/www/html"]
volumes:
  mysql: {}